const TRIPS = [
    {
        id: 1,
        name: "Sněžka",
        category: "turistika",
        icon: "🥾",
        region: "Krkonoše",
        lat: 50.7363,
        lon: 15.7394,
        description: "Nejvyšší hora České republiky (1 603 m n.m.). Výstup z Pece pod Sněžkou přes Obří důl nebo lanovkou. Na vrcholu meteorologická stanice a kaple sv. Vavřince.",
        difficulty: "střední",
        duration: "4–5 hod",
        distance: "8 km",
        elevation: "+780 m",
        mapyCzUrl: "https://mapy.cz/turisticka?x=15.7394&y=50.7363&z=13&source=coor&id=15.7394%2C50.7363"
    },
    {
        id: 2,
        name: "Praděd",
        category: "turistika",
        icon: "🥾",
        region: "Jeseníky",
        lat: 50.0847,
        lon: 17.2325,
        description: "Nejvyšší hora Moravy a Slezska (1 492 m n.m.). Charakteristická televizní věž na vrcholu, krásné výhledy do Polska i Slovenska. Výstup z Ovčárny.",
        difficulty: "lehká",
        duration: "2–3 hod",
        distance: "6 km",
        elevation: "+320 m",
        mapyCzUrl: "https://mapy.cz/turisticka?x=17.2325&y=50.0847&z=13&source=coor&id=17.2325%2C50.0847"
    },
    {
        id: 3,
        name: "Říp",
        category: "turistika",
        icon: "🥾",
        region: "Střední Čechy",
        lat: 50.3683,
        lon: 14.2711,
        description: "Posvátná hora českého národa (456 m n.m.). Hora Čechů podle pověsti o praotci Čechovi. Na vrcholu románská rotunda sv. Jiří z 12. století.",
        difficulty: "lehká",
        duration: "1–2 hod",
        distance: "4 km",
        elevation: "+140 m",
        mapyCzUrl: "https://mapy.cz/turisticka?x=14.2711&y=50.3683&z=13&source=coor&id=14.2711%2C50.3683"
    },
    {
        id: 4,
        name: "Máchovo jezero",
        category: "jezero",
        icon: "🏊",
        region: "Česká Lípa",
        lat: 50.6033,
        lon: 14.6778,
        description: "Největší přírodní jezero Čech, oblíbené letní středisko. Obklopeno borovými lesy, skvělé pro koupání, rybaření i cyklistiku. V okolí hrad Bezděz.",
        difficulty: "lehká",
        duration: "3–4 hod",
        distance: "12 km",
        elevation: "+30 m",
        mapyCzUrl: "https://mapy.cz/turisticka?x=14.6778&y=50.6033&z=13&source=coor&id=14.6778%2C50.6033"
    },
    {
        id: 5,
        name: "Lipno",
        category: "jezero",
        icon: "🏊",
        region: "Jihočeský kraj",
        lat: 48.6369,
        lon: 14.2101,
        description: "Největší vodní nádrž v ČR na řece Vltavě. Ideální pro plavbu na lodích, kite-surfing a cyklistiku podél břehů. V zimě populární pro in-line bruslení.",
        difficulty: "lehká",
        duration: "celý den",
        distance: "20 km",
        elevation: "+20 m",
        mapyCzUrl: "https://mapy.cz/turisticka?x=14.2101&y=48.6369&z=12&source=coor&id=14.2101%2C48.6369"
    },
    {
        id: 6,
        name: "Brněnská přehrada",
        category: "jezero",
        icon: "🏊",
        region: "Brno",
        lat: 49.2572,
        lon: 16.5216,
        description: "Přehrada na řece Svratce přímo u Brna, oblíbené místo místních. Pravidelné lodní výlety, plážový bar, paddleboardy a mnohé restaurace podél břehu.",
        difficulty: "lehká",
        duration: "2–3 hod",
        distance: "8 km",
        elevation: "+10 m",
        mapyCzUrl: "https://mapy.cz/turisticka?x=16.5216&y=49.2572&z=13&source=coor&id=16.5216%2C49.2572"
    },
    {
        id: 7,
        name: "Karlštejn",
        category: "hrad",
        icon: "🏰",
        region: "Střední Čechy",
        lat: 49.9394,
        lon: 14.1883,
        description: "Nejnavštěvovanější hrad v ČR, gotický klenot Karla IV. (14. stol.). Bývalé úložiště korunovačních klenotů. Výstup přes malebné údolí řeky Berounky.",
        difficulty: "lehká",
        duration: "3–4 hod",
        distance: "7 km",
        elevation: "+200 m",
        mapyCzUrl: "https://mapy.cz/turisticka?x=14.1883&y=49.9394&z=14&source=coor&id=14.1883%2C49.9394"
    },
    {
        id: 8,
        name: "Hrad Bouzov",
        category: "hrad",
        icon: "🏰",
        region: "Olomoucký kraj",
        lat: 49.7022,
        lon: 16.8839,
        description: "Pohádkový hrad na Moravě s romantickou pozdně gotickou podobou. Řád německých rytířů ho přestavěl na konci 19. stol. Ideální výlet pro celou rodinu.",
        difficulty: "lehká",
        duration: "2–3 hod",
        distance: "4 km",
        elevation: "+100 m",
        mapyCzUrl: "https://mapy.cz/turisticka?x=16.8839&y=49.7022&z=14&source=coor&id=16.8839%2C49.7022"
    },
    {
        id: 9,
        name: "Kokoín",
        category: "hrad",
        icon: "🏰",
        region: "Střední Čechy",
        lat: 50.4394,
        lon: 14.5856,
        description: "Gotický hrad v malebné krajině Kokořínska, obklopen pískovcovými skalami. Procházka po chráněné krajinné oblasti s mnoha jeskyněmi a zajímavými skalními útvary.",
        difficulty: "lehká",
        duration: "3–4 hod",
        distance: "10 km",
        elevation: "+150 m",
        mapyCzUrl: "https://mapy.cz/turisticka?x=14.5856&y=50.4394&z=13&source=coor&id=14.5856%2C50.4394"
    },
    {
        id: 10,
        name: "Pravčická brána",
        category: "priroda",
        icon: "🌿",
        region: "České Švýcarsko",
        lat: 50.8808,
        lon: 14.2758,
        description: "Největší přírodní pískovcová brána v Evropě (výška 16 m, šířka 26 m). Srdce Národního parku České Švýcarsko. Ikonické místo, filmové kulisy mnoha snímků.",
        difficulty: "lehká",
        duration: "3–4 hod",
        distance: "9 km",
        elevation: "+300 m",
        mapyCzUrl: "https://mapy.cz/turisticka?x=14.2758&y=50.8808&z=13&source=coor&id=14.2758%2C50.8808"
    },
    {
        id: 11,
        name: "Prachovské skály",
        category: "priroda",
        icon: "🌿",
        region: "Jičínsko",
        lat: 50.4444,
        lon: 15.2603,
        description: "Skalní labyrint v srdci Českého ráje. Úzké soutěsky, vyhlídky a malebné vyhlídkové věže, obklopené hustými lesy. Výchozí bod pro procházky do celého Českého ráje.",
        difficulty: "lehká",
        duration: "2–3 hod",
        distance: "6 km",
        elevation: "+120 m",
        mapyCzUrl: "https://mapy.cz/turisticka?x=15.2603&y=50.4444&z=13&source=coor&id=15.2603%2C50.4444"
    },
    {
        id: 12,
        name: "Ještěd",
        category: "vyhlídka",
        icon: "👁️",
        region: "Liberec",
        lat: 50.7259,
        lon: 15.1011,
        description: "Ikonický vysílač-hotel na vrcholu hory Ještěd (1 012 m n.m.), dílo architekta Karla Hubáčka (Pritzkerova cena 1995). Výhledy na Liberec, Krkonoše i Jizerské hory.",
        difficulty: "střední",
        duration: "3–4 hod",
        distance: "8 km",
        elevation: "+500 m",
        mapyCzUrl: "https://mapy.cz/turisticka?x=15.1011&y=50.7259&z=13&source=coor&id=15.1011%2C50.7259"
    },
    {
        id: 13,
        name: "Milešovka",
        category: "vyhlídka",
        icon: "👁️",
        region: "České Středohoří",
        lat: 50.5539,
        lon: 13.9317,
        description: "Meteorologická hora Českého středohoří (837 m n.m.). Za jasného počasí výhled přes celé Čechy. Typický sopečný kužel obklopený vinicemi a chmelnicemi.",
        difficulty: "střední",
        duration: "2–3 hod",
        distance: "7 km",
        elevation: "+420 m",
        mapyCzUrl: "https://mapy.cz/turisticka?x=13.9317&y=50.5539&z=13&source=coor&id=13.9317%2C50.5539"
    },
    {
        id: 14,
        name: "Divoká Šárka",
        category: "priroda",
        icon: "🌿",
        region: "Praha",
        lat: 50.0994,
        lon: 14.3342,
        description: "Přírodní rezervace přímo v Praze – hluboké údolí potoka Šárky s koupacím jezerem, skalkami a lesními stezkami. Skvělý únik z města bez nutnosti dalekého cestování.",
        difficulty: "lehká",
        duration: "1–2 hod",
        distance: "4 km",
        elevation: "+80 m",
        mapyCzUrl: "https://mapy.cz/turisticka?x=14.3342&y=50.0994&z=14&source=coor&id=14.3342%2C50.0994"
    },
    {
        id: 15,
        name: "Třeboňsko – rybníky",
        category: "jezero",
        icon: "🏊",
        region: "Jihočeský kraj",
        lat: 49.0027,
        lon: 14.7708,
        description: "Krajina tisíce rybníků – Rozmberk, Svět, Opatovický – s unikátní přírodou biosférické rezervace. Ideální pro cyklistiku, birdwatching a relaxaci v klidu přírody.",
        difficulty: "lehká",
        duration: "celý den",
        distance: "25 km",
        elevation: "+20 m",
        mapyCzUrl: "https://mapy.cz/turisticka?x=14.7708&y=49.0027&z=12&source=coor&id=14.7708%2C49.0027"
    }
];

const CATEGORY_LABELS = {
    vse:       "Vše",
    turistika: "Turistika",
    jezero:    "Jezero",
    hrad:      "Hrad",
    priroda:   "Příroda",
    vyhlídka:  "Vyhlídka"
};

const DIFF_LABELS = {
    "lehká":   { cls: "diff-lehka",   label: "Lehká" },
    "střední": { cls: "diff-stredni", label: "Střední" },
    "těžká":   { cls: "diff-tezka",   label: "Těžká" }
};
